/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SupplierManagement;

/**
 *
 * @author Jengsiang
 */
import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;
import java.util.*;
public class UI extends javax.swing.JFrame {
    
    private SupplierManagement sm;
    private DefaultTableModel model;
    
    public UI() {
        initComponents();
        SupplierID_TextField.setEditable(false);
        String[] columns = {"No.","Supplier ID", "Supplier Name", "Supplier Contact Number", "Supplier Email", "Supplier Address", "Item Description"};
        model = new DefaultTableModel(columns, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        SupplierTable.setModel(model);
        
        sm = new SupplierManagement(
            SupplierTable,
            SupplierID_TextField,
            SupplierName_TextField,
            SupplierContact_TextField,
            SupplierEmail_TextField,
            SupplierAddress_TextField,
            SupplierItemDescription_TextField
        );
        
        sm.refresh();
        
        SupplierTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = SupplierTable.getSelectedRow();
                if (selectedRow != -1) {
                    String supplierID = SupplierTable.getValueAt(selectedRow, 1).toString();
                    String supplierName = SupplierTable.getValueAt(selectedRow, 2).toString();
                    String supplierContact = SupplierTable.getValueAt(selectedRow, 3).toString();
                    String supplierEmail = SupplierTable.getValueAt(selectedRow, 4).toString();
                    String supplierAddress = SupplierTable.getValueAt(selectedRow, 5).toString();
                    String itemDescription = SupplierTable.getValueAt(selectedRow, 6).toString();

                    SupplierID_TextField.setText(supplierID);
                    SupplierName_TextField.setText(supplierName);
                    SupplierContact_TextField.setText(supplierContact);
                    SupplierEmail_TextField.setText(supplierEmail);
                    SupplierAddress_TextField.setText(supplierAddress);
                    SupplierItemDescription_TextField.setText(itemDescription);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        NAVPanel = new javax.swing.JPanel();
        NAVBAR = new javax.swing.JLabel();
        SupplierID = new javax.swing.JLabel();
        SupplierID_TextField = new javax.swing.JTextField();
        SupplierName = new javax.swing.JLabel();
        SupplierName_TextField = new javax.swing.JTextField();
        SupplierContact = new javax.swing.JLabel();
        SupplierContact_TextField = new javax.swing.JTextField();
        SupplierEmail = new javax.swing.JLabel();
        SupplierEmail_TextField = new javax.swing.JTextField();
        SupplierAddress = new javax.swing.JLabel();
        SupplierAddress_TextField = new javax.swing.JTextField();
        SupplierItemDescription = new javax.swing.JLabel();
        SupplierItemDescription_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));

        NAVPanel.setBackground(new java.awt.Color(204, 204, 204));
        NAVPanel.setPreferredSize(new java.awt.Dimension(156, 720));

        NAVBAR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NAVBAR.setForeground(new java.awt.Color(0, 0, 0));
        NAVBAR.setText("NAV BAR");

        javax.swing.GroupLayout NAVPanelLayout = new javax.swing.GroupLayout(NAVPanel);
        NAVPanel.setLayout(NAVPanelLayout);
        NAVPanelLayout.setHorizontalGroup(
            NAVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAVPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NAVBAR)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        NAVPanelLayout.setVerticalGroup(
            NAVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAVPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(NAVBAR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SupplierID.setForeground(new java.awt.Color(0, 0, 0));
        SupplierID.setText("Supplier ID :");

        SupplierID_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierID_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SupplierName.setForeground(new java.awt.Color(0, 0, 0));
        SupplierName.setText("Supplier Name :");

        SupplierName_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierName_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SupplierName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierName_TextFieldActionPerformed(evt);
            }
        });

        SupplierContact.setForeground(new java.awt.Color(0, 0, 0));
        SupplierContact.setText("Contact Number :");

        SupplierContact_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierContact_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SupplierEmail.setForeground(new java.awt.Color(0, 0, 0));
        SupplierEmail.setText("Email : ");

        SupplierEmail_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierEmail_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SupplierAddress.setForeground(new java.awt.Color(0, 0, 0));
        SupplierAddress.setText("Address :");

        SupplierAddress_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierAddress_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SupplierItemDescription.setForeground(new java.awt.Color(0, 0, 0));
        SupplierItemDescription.setText("Item Description : ");

        SupplierItemDescription_TextField.setBackground(new java.awt.Color(204, 204, 204));
        SupplierItemDescription_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SupplierTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SupplierTable.getTableHeader().setReorderingAllowed(false);
        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Supplier ID", "Supplier Name", "Contact Number", "Email", "Address", "Item Description"
            }
        ));
        SupplierTable.setShowGrid(true);
        jScrollPane1.setViewportView(SupplierTable);
        SupplierTable.getAccessibleContext().setAccessibleDescription("");

        Add.setBackground(new java.awt.Color(153, 255, 153));
        Add.setForeground(new java.awt.Color(0, 0, 0));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(153, 255, 153));
        Update.setForeground(new java.awt.Color(0, 0, 0));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 51, 51));
        Clear.setForeground(new java.awt.Color(0, 0, 0));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 51, 51));
        Delete.setForeground(new java.awt.Color(0, 0, 0));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Refresh.setBackground(new java.awt.Color(153, 153, 153));
        Refresh.setForeground(new java.awt.Color(0, 0, 0));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(NAVPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SupplierContact)
                                    .addComponent(SupplierEmail)
                                    .addComponent(SupplierName)
                                    .addComponent(SupplierID)
                                    .addComponent(SupplierAddress)
                                    .addComponent(SupplierItemDescription))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SupplierItemDescription_TextField)
                                            .addComponent(SupplierAddress_TextField)
                                            .addComponent(SupplierEmail_TextField)
                                            .addComponent(SupplierContact_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SupplierID_TextField)
                                        .addComponent(SupplierName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Refresh)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Add)
                        .addGap(18, 18, 18)
                        .addComponent(Clear)
                        .addGap(18, 18, 18)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NAVPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(SupplierID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierName))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierContact_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierContact))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierEmail_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierEmail))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierAddress))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierItemDescription_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierItemDescription))
                        .addGap(194, 194, 194)
                        .addComponent(Refresh))
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SupplierID)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(Clear))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        //ADD
        System.out.println("Add button clicked!");
        sm.add();
    }//GEN-LAST:event_AddActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        //Clear
        sm.clear();
    }//GEN-LAST:event_ClearActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        //Update
        sm.update();
        sm.refresh();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        //Delete
        sm.delete();
        sm.refresh();
    }//GEN-LAST:event_DeleteActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        //Refresh
        sm.refresh();
    }//GEN-LAST:event_RefreshActionPerformed

    private void SupplierName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierName_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel Background;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel NAVBAR;
    private javax.swing.JPanel NAVPanel;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel SupplierAddress;
    private javax.swing.JTextField SupplierAddress_TextField;
    private javax.swing.JLabel SupplierContact;
    private javax.swing.JTextField SupplierContact_TextField;
    private javax.swing.JLabel SupplierEmail;
    private javax.swing.JTextField SupplierEmail_TextField;
    private javax.swing.JLabel SupplierID;
    private javax.swing.JTextField SupplierID_TextField;
    private javax.swing.JLabel SupplierItemDescription;
    private javax.swing.JTextField SupplierItemDescription_TextField;
    private javax.swing.JLabel SupplierName;
    private javax.swing.JTextField SupplierName_TextField;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
