/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PurchaseOrder;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PO_Approval extends javax.swing.JFrame {
    
    private PO_GenerationManagement PO;
    private DefaultTableModel model;
    
    public PO_Approval() {
        initComponents();
        PO = new PO_GenerationManagement();
        model = new DefaultTableModel(
                new String[]{"No", "PO ID", "PR ID", "Date", "Purchase Manager Name", "Purchase Manager ID", 
                    "Sales Manager Name", "Sales Manager ID", "Expected Delivery Date", "Supplier Name",
                    "Supplier ID",  "Item Name", "Item Code", "Quantity", "Status", "Finance Manager Name", "Finance Manager ID", "Payment Status"}, 
                0 );
        
        POApprovalTable.setModel(model);

        displayPOTable();
    }
    
    private void displayPOTable() {
        model.setRowCount(0);

        List<PurchaseOrder> poList = PO_GenerationManagement.getAllPurchaseOrders(); 
        int no = 1;
        for (PurchaseOrder po : poList) {
            if (!"Pending".equalsIgnoreCase(po.getStatus())) {
                continue;  // Skip non-pending
            }
            String supplierName = po.getSP_Name().replace("{", "").replace("}", "");
            String supplierID = po.getSP_ID().replace("{", "").replace("}", "");
            String itemName = po.getItemName().replace("{", "").replace("}", "");
            String itemCode = po.getItemCode().replace("{", "").replace("}", "");

            // Use the full quantity string from the map
            String quantity = PO_GenerationManagement.getOriginalQuantity(po.getPO_ID());

            Object[] rowData = {
                no++,
                po.getPO_ID(),
                po.getPR_ID(),
                po.getDate(),
                po.getPM_Name(),
                po.getPM_ID(),
                po.getSM_Name(),
                po.getSM_ID(),
                po.getExpectedDeliveryDate(),
                supplierName,
                supplierID,
                itemName,
                itemCode,
                quantity,
                po.getStatus(),
                po.getFM_Name(),
                po.getFM_ID(),
                po.getPaymentStatus()
            };
            model.addRow(rowData);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        POApprovalTable = new javax.swing.JTable();
        ApprovalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        POApprovalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Purchase Order ID", "Purchase Requisition ID", "Date", "Sales Manager Name", "Sales Manager ID", "Purchase Manager Name", "Purchase Manager ID", "Item Code", "Item Name", "Supplier ID", "Supplier Name", "Quantity", "Expected Delivery Date", "Purchase Order Status"
            }
        ));
        jScrollPane1.setViewportView(POApprovalTable);

        ApprovalButton.setText("Approvall Form");
        ApprovalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprovalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(ApprovalButton)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(ApprovalButton)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApprovalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprovalButtonActionPerformed
        // Edit
        int selectedRow = POApprovalTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a Purchase Order to approve.");
            return;
        }
        // Get the PO ID from the table
        String poID = (String) model.getValueAt(selectedRow, 1); // Column 1 is "PO ID"
        // Find the PO object from the list
        List<PurchaseOrder> POList = PO.getAllPurchaseOrders();
        PurchaseOrder selectedPO = null;
        for (PurchaseOrder po : POList) {
            if (po.getPO_ID().equals(poID)) {
                selectedPO = po;
                break;
            }
        }

        if (selectedPO != null) {
            PO_Approve approveForm = new PO_Approve(selectedPO); // Pass full PO object
            approveForm.setVisible(true);
            this.dispose(); // optional: close the current window
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected PO data not found.");
        }
    }//GEN-LAST:event_ApprovalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PO_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PO_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PO_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PO_Approval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PO_Approval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApprovalButton;
    private javax.swing.JTable POApprovalTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
